
import AppPackage.AnimationClass;
import Graphics.AnimationDesign;
import Graphics.Design;
import java.awt.Color;
import java.awt.Point;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hank
 */
public class MainFrame extends javax.swing.JFrame {

    
    boolean panelOpen = false;
    AnimationClass aniClass = new AnimationClass();
    ImageIcon panelOpenButton = new ImageIcon(getClass().getResource("Images\\panelOpenButton.png"));
    
    Recognizer reco;
    
    public MainFrame() throws MalformedURLException {
        setUndecorated(true);
        setBackground(new Color(0, 0,0,0));
        initComponents();
        setLocation(new Point(150, 70));
        
        Design.makeTransparentPanel(jPanel1);
        Design.makeTransparentPanel(mainPanel);
        Design.makeTransparentPanel(homePanel);
        Design.makeTransparentPanel(homeAutomationParent);
        Design.makeTransparentPanel(bedRoomPanel);
        Design.makeTransparentPanel(AutomationHomePanel);
        Design.makeTransparentPanel(VideoPlayerPanel);
        Design.makeTransparentPanel(infoExtractPanel);
        //Design.makeTransparentPanel(playerScreenPanel);
        
        Design.makeTrasparenttextField(inputField);
        
        mainPanel.removeAll();
        mainPanel.add(homePanel);
        mainPanel.revalidate();    
        
        // === Recoginizer ====
        
        reco = new Recognizer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ExitButton = new javax.swing.JLabel();
        MinimizeButton = new javax.swing.JLabel();
        panelOpenClose = new javax.swing.JLabel();
        panelBtn1 = new javax.swing.JLabel();
        panelBtn2 = new javax.swing.JLabel();
        panelBtn3 = new javax.swing.JLabel();
        panelBtn4 = new javax.swing.JLabel();
        panelBtn5 = new javax.swing.JLabel();
        panelBtn6 = new javax.swing.JLabel();
        sidePanel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        homeAutoBtn = new javax.swing.JLabel();
        infoExtractorBtn = new javax.swing.JLabel();
        videoPlayerBtn = new javax.swing.JLabel();
        voiceBrowserBtn = new javax.swing.JLabel();
        dailyNewsReaderBtn = new javax.swing.JLabel();
        mp3PlayerBtn = new javax.swing.JLabel();
        homeAuto = new javax.swing.JLabel();
        infoExtractor = new javax.swing.JLabel();
        videoPlayer = new javax.swing.JLabel();
        voiceBrowser = new javax.swing.JLabel();
        dailyNewsReader = new javax.swing.JLabel();
        mp3Player = new javax.swing.JLabel();
        homeAutomationParent = new javax.swing.JPanel();
        AutomationHomePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bedRoom = new javax.swing.JLabel();
        livingRoom = new javax.swing.JLabel();
        personalRoom = new javax.swing.JLabel();
        storeRoom = new javax.swing.JLabel();
        kitchen = new javax.swing.JLabel();
        bedRoomPanel = new javax.swing.JPanel();
        bedRoomTVBtn = new javax.swing.JLabel();
        bedRoomACBtn = new javax.swing.JLabel();
        bedRoomFanBtn = new javax.swing.JLabel();
        BedRoomNightLightBtn = new javax.swing.JLabel();
        bedRoomLightBtn = new javax.swing.JLabel();
        bedRoomPanelBorder = new javax.swing.JLabel();
        infoExtractPanel = new javax.swing.JPanel();
        VideoPlayerPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        canvas1 = new java.awt.Canvas();
        inputField = new javax.swing.JTextField();
        playerBorder = new javax.swing.JLabel();
        player_inputField = new javax.swing.JLabel();
        player_playButton = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1002, 670));
        setSize(new java.awt.Dimension(950, 650));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButtonMouseClicked(evt);
            }
        });
        jPanel1.add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 12, 20, 20));

        MinimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeButtonMouseClicked(evt);
            }
        });
        jPanel1.add(MinimizeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 12, 20, 20));

        panelOpenClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sidePanel/open Button.png"))); // NOI18N
        panelOpenClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelOpenCloseMouseClicked(evt);
            }
        });
        jPanel1.add(panelOpenClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 340, 30, 30));

        panelBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sidePanel/btn 1.png"))); // NOI18N
        panelBtn1.setPreferredSize(new java.awt.Dimension(250, 42));
        panelBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBtn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBtn1MouseExited(evt);
            }
        });
        jPanel1.add(panelBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1003, 150, -1, -1));

        panelBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sidePanel/btn 2.png"))); // NOI18N
        panelBtn2.setPreferredSize(new java.awt.Dimension(250, 42));
        panelBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBtn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBtn2MouseExited(evt);
            }
        });
        jPanel1.add(panelBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1003, 205, 250, -1));

        panelBtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sidePanel/btn 3.png"))); // NOI18N
        panelBtn3.setPreferredSize(new java.awt.Dimension(250, 42));
        panelBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBtn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBtn3MouseExited(evt);
            }
        });
        jPanel1.add(panelBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1003, 260, 250, -1));

        panelBtn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sidePanel/btn 4.png"))); // NOI18N
        panelBtn4.setPreferredSize(new java.awt.Dimension(250, 42));
        panelBtn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBtn4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBtn4MouseExited(evt);
            }
        });
        jPanel1.add(panelBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1003, 315, 250, -1));

        panelBtn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sidePanel/btn 5.png"))); // NOI18N
        panelBtn5.setPreferredSize(new java.awt.Dimension(250, 42));
        panelBtn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBtn5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBtn5MouseExited(evt);
            }
        });
        jPanel1.add(panelBtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1003, 370, 250, -1));

        panelBtn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sidePanel/btn 6.png"))); // NOI18N
        panelBtn6.setPreferredSize(new java.awt.Dimension(250, 42));
        panelBtn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBtn6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBtn6MouseExited(evt);
            }
        });
        jPanel1.add(panelBtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1003, 425, 250, -1));

        sidePanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sidePanel/background.png"))); // NOI18N
        sidePanel.setPreferredSize(new java.awt.Dimension(300, 552));
        jPanel1.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(953, 72, 290, -1));

        mainPanel.setLayout(new java.awt.CardLayout());

        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeAutoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeAutoBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeAutoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeAutoBtnMouseExited(evt);
            }
        });
        homePanel.add(homeAutoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 120, 120));

        infoExtractorBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoExtractorBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                infoExtractorBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                infoExtractorBtnMouseExited(evt);
            }
        });
        homePanel.add(infoExtractorBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 120, 120));

        videoPlayerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                videoPlayerBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                videoPlayerBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                videoPlayerBtnMouseExited(evt);
            }
        });
        homePanel.add(videoPlayerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 110, 120, 120));

        voiceBrowserBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                voiceBrowserBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                voiceBrowserBtnMouseExited(evt);
            }
        });
        homePanel.add(voiceBrowserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 280, 120, 120));

        dailyNewsReaderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dailyNewsReaderBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dailyNewsReaderBtnMouseExited(evt);
            }
        });
        homePanel.add(dailyNewsReaderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 280, 120, 120));

        mp3PlayerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mp3PlayerBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mp3PlayerBtnMouseExited(evt);
            }
        });
        homePanel.add(mp3PlayerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 120, 120));

        homeAuto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mainPanel/Home Automation.png"))); // NOI18N
        homePanel.add(homeAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        infoExtractor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mainPanel/Info Extractor.png"))); // NOI18N
        homePanel.add(infoExtractor, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 110, -1, -1));

        videoPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mainPanel/Video Player.png"))); // NOI18N
        homePanel.add(videoPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 110, -1, -1));

        voiceBrowser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mainPanel/Voice Browser.png"))); // NOI18N
        homePanel.add(voiceBrowser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        dailyNewsReader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mainPanel/Daily News Reader.png"))); // NOI18N
        homePanel.add(dailyNewsReader, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 280, -1, -1));

        mp3Player.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mainPanel/Mp3 Player.png"))); // NOI18N
        homePanel.add(mp3Player, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 280, -1, -1));

        mainPanel.add(homePanel, "card2");

        homeAutomationParent.setLayout(new java.awt.CardLayout());

        AutomationHomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        AutomationHomePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 120, 120));

        bedRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeAutomation/Bed Room.png"))); // NOI18N
        AutomationHomePanel.add(bedRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        livingRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeAutomation/Living Room.png"))); // NOI18N
        AutomationHomePanel.add(livingRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        personalRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeAutomation/Personal Room.png"))); // NOI18N
        AutomationHomePanel.add(personalRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        storeRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeAutomation/Store Room.png"))); // NOI18N
        AutomationHomePanel.add(storeRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 275, -1, -1));

        kitchen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeAutomation/Kitchen.png"))); // NOI18N
        AutomationHomePanel.add(kitchen, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 275, -1, -1));

        homeAutomationParent.add(AutomationHomePanel, "card2");

        bedRoomPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bedRoomTVBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeAutomation/bedRoom/TV W.png"))); // NOI18N
        bedRoomPanel.add(bedRoomTVBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        bedRoomACBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeAutomation/bedRoom/AC W.png"))); // NOI18N
        bedRoomPanel.add(bedRoomACBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        bedRoomFanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeAutomation/bedRoom/Fan W.png"))); // NOI18N
        bedRoomPanel.add(bedRoomFanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));

        BedRoomNightLightBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeAutomation/bedRoom/Night Light W.png"))); // NOI18N
        bedRoomPanel.add(BedRoomNightLightBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        bedRoomLightBtn.setForeground(new java.awt.Color(255, 0, 51));
        bedRoomLightBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeAutomation/bedRoom/Room Light W.png"))); // NOI18N
        bedRoomPanel.add(bedRoomLightBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        bedRoomPanelBorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeAutomation/bedRoom/bed Room Border.png"))); // NOI18N
        bedRoomPanel.add(bedRoomPanelBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 26, -1, -1));

        homeAutomationParent.add(bedRoomPanel, "card3");

        mainPanel.add(homeAutomationParent, "card3");

        javax.swing.GroupLayout infoExtractPanelLayout = new javax.swing.GroupLayout(infoExtractPanel);
        infoExtractPanel.setLayout(infoExtractPanelLayout);
        infoExtractPanelLayout.setHorizontalGroup(
            infoExtractPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        infoExtractPanelLayout.setVerticalGroup(
            infoExtractPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        mainPanel.add(infoExtractPanel, "card4");

        VideoPlayerPanel.setForeground(new java.awt.Color(255, 255, 255));
        VideoPlayerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(canvas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 280));

        VideoPlayerPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 440, 280));

        inputField.setFont(new java.awt.Font("Minion Pro SmBd", 2, 14)); // NOI18N
        inputField.setForeground(new java.awt.Color(255, 255, 255));
        inputField.setToolTipText("search");
        inputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFieldActionPerformed(evt);
            }
        });
        VideoPlayerPanel.add(inputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 42, 215, 27));

        playerBorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/videoPlayer/border.png"))); // NOI18N
        VideoPlayerPanel.add(playerBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        player_inputField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/videoPlayer/input field.png"))); // NOI18N
        VideoPlayerPanel.add(player_inputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, -1, -1));

        player_playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/videoPlayer/play button.png"))); // NOI18N
        player_playButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                player_playButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                player_playButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                player_playButtonMouseExited(evt);
            }
        });
        VideoPlayerPanel.add(player_playButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, -1, -1));

        mainPanel.add(VideoPlayerPanel, "card5");

        jPanel1.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 950, 480));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.png"))); // NOI18N
        background.setMaximumSize(new java.awt.Dimension(1002, 630));
        background.setMinimumSize(new java.awt.Dimension(1002, 630));
        background.setPreferredSize(new java.awt.Dimension(1002, 650));
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1002, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseClicked
          System.exit(0);
    }//GEN-LAST:event_ExitButtonMouseClicked

    private void panelOpenCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOpenCloseMouseClicked
       if(!panelOpen)
       {
            aniClass.jLabelXLeft(953,713, 4 ,10 , sidePanel);
            aniClass.jLabelXLeft(1003,763, 4 ,10 , panelBtn1);
            aniClass.jLabelXLeft(1003,763, 4 ,10 , panelBtn2);
            aniClass.jLabelXLeft(1003,763, 4 ,10, panelBtn3);
            aniClass.jLabelXLeft(1003,763, 4 ,10, panelBtn4);
            aniClass.jLabelXLeft(1003,763, 4 ,10, panelBtn5);
            aniClass.jLabelXLeft(1003,763, 4 ,10, panelBtn6);
            aniClass.jLabelXLeft(970,730, 4 ,10, panelOpenClose);
            
            panelOpen = true;
        }
           
        else
       {
            aniClass.jLabelXRight(713, 953, 4, 10 , sidePanel);
            aniClass.jLabelXRight(763, 1003, 4, 10, panelBtn1);
            aniClass.jLabelXRight(763,1003, 4 ,10 , panelBtn2);
            aniClass.jLabelXRight(763,1003, 4 ,10, panelBtn3);
            aniClass.jLabelXRight(763,1003, 4 ,10, panelBtn4);
            aniClass.jLabelXRight(763,1003, 4 ,10, panelBtn5);
            aniClass.jLabelXRight(763,1003, 4 ,10, panelBtn6);
            aniClass.jLabelXRight(730,970, 4 ,10, panelOpenClose);
            
            panelOpen = false;
       }
    }//GEN-LAST:event_panelOpenCloseMouseClicked

    
  
    
    private void panelBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBtn1MouseEntered
        panelBtn1.setIcon(Images.btn1Hover);
    }//GEN-LAST:event_panelBtn1MouseEntered

    private void panelBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBtn1MouseExited
        panelBtn1.setIcon(Images.btn1);
    }//GEN-LAST:event_panelBtn1MouseExited

    private void panelBtn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBtn2MouseEntered
        panelBtn2.setIcon(Images.btn2Hover);
    }//GEN-LAST:event_panelBtn2MouseEntered

    private void panelBtn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBtn2MouseExited
        panelBtn2.setIcon(Images.btn2);
    }//GEN-LAST:event_panelBtn2MouseExited

    private void panelBtn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBtn3MouseEntered
        panelBtn3.setIcon(Images.btn3Hover);
    }//GEN-LAST:event_panelBtn3MouseEntered

    private void panelBtn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBtn3MouseExited
        panelBtn3.setIcon(Images.btn3);
    }//GEN-LAST:event_panelBtn3MouseExited

    private void panelBtn4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBtn4MouseEntered
        panelBtn4.setIcon(Images.btn4Hover);
    }//GEN-LAST:event_panelBtn4MouseEntered

    private void panelBtn4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBtn4MouseExited
        panelBtn4.setIcon(Images.btn4);
    }//GEN-LAST:event_panelBtn4MouseExited

    private void panelBtn5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBtn5MouseEntered
        panelBtn5.setIcon(Images.btn5Hover);
    }//GEN-LAST:event_panelBtn5MouseEntered

    private void panelBtn5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBtn5MouseExited
        panelBtn5.setIcon(Images.btn5);
    }//GEN-LAST:event_panelBtn5MouseExited

    private void panelBtn6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBtn6MouseEntered
        panelBtn6.setIcon(Images.btn6Hover);
    }//GEN-LAST:event_panelBtn6MouseEntered

    private void panelBtn6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBtn6MouseExited
        panelBtn6.setIcon(Images.btn6);
    }//GEN-LAST:event_panelBtn6MouseExited

    private void homeAutoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeAutoBtnMouseEntered
        homeAuto.setIcon(Images.homeAutoHover);
    }//GEN-LAST:event_homeAutoBtnMouseEntered

    private void homeAutoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeAutoBtnMouseExited
        homeAuto.setIcon(Images.homeAuto);
    }//GEN-LAST:event_homeAutoBtnMouseExited

    private void infoExtractorBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoExtractorBtnMouseClicked
        AnimationDesign.changePanel(mainPanel,infoExtractPanel);
    }//GEN-LAST:event_infoExtractorBtnMouseClicked

    private void infoExtractorBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoExtractorBtnMouseEntered
        infoExtractor.setIcon(Images.infoExHover);
    }//GEN-LAST:event_infoExtractorBtnMouseEntered

    private void infoExtractorBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoExtractorBtnMouseExited
        infoExtractor.setIcon(Images.infoEx);
    }//GEN-LAST:event_infoExtractorBtnMouseExited

    private void videoPlayerBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_videoPlayerBtnMouseEntered
        videoPlayer.setIcon(Images.videoPlayerHover);
    }//GEN-LAST:event_videoPlayerBtnMouseEntered

    private void videoPlayerBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_videoPlayerBtnMouseExited
        videoPlayer.setIcon(Images.videoPlayer);
    }//GEN-LAST:event_videoPlayerBtnMouseExited

    private void voiceBrowserBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voiceBrowserBtnMouseEntered
        voiceBrowser.setIcon(Images.voiceBrowserHover);
    }//GEN-LAST:event_voiceBrowserBtnMouseEntered

    private void voiceBrowserBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voiceBrowserBtnMouseExited
        voiceBrowser.setIcon(Images.voiceBrowser);
    }//GEN-LAST:event_voiceBrowserBtnMouseExited

    private void dailyNewsReaderBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dailyNewsReaderBtnMouseEntered
        dailyNewsReader.setIcon(Images.DailyNewsHover);
    }//GEN-LAST:event_dailyNewsReaderBtnMouseEntered

    private void dailyNewsReaderBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dailyNewsReaderBtnMouseExited
        dailyNewsReader.setIcon(Images.DailyNews);
    }//GEN-LAST:event_dailyNewsReaderBtnMouseExited

    private void mp3PlayerBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mp3PlayerBtnMouseEntered
       mp3Player.setIcon(Images.mp3PlayerHover);
    }//GEN-LAST:event_mp3PlayerBtnMouseEntered

    private void mp3PlayerBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mp3PlayerBtnMouseExited
        mp3Player.setIcon(Images.mp3Player);
    }//GEN-LAST:event_mp3PlayerBtnMouseExited

    private void homeAutoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeAutoBtnMouseClicked
           AnimationDesign.changePanel(mainPanel,homeAutomationParent);
           
    }//GEN-LAST:event_homeAutoBtnMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        AnimationDesign.changePanel(homeAutomationParent,bedRoomPanel); 
    }//GEN-LAST:event_jLabel2MouseClicked

    private void videoPlayerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_videoPlayerBtnMouseClicked
        AnimationDesign.changePanel(mainPanel,VideoPlayerPanel);
    }//GEN-LAST:event_videoPlayerBtnMouseClicked

    private void panelBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBtn1MouseClicked
        AnimationDesign.changePanel(homeAutomationParent,AutomationHomePanel);
        AnimationDesign.changePanel(mainPanel,homePanel);
    }//GEN-LAST:event_panelBtn1MouseClicked

    private void player_playButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player_playButtonMouseEntered
        player_playButton.setIcon(Images.playButtonShadow);
    }//GEN-LAST:event_player_playButtonMouseEntered

    private void player_playButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player_playButtonMouseExited
         player_playButton.setIcon(Images.playButton);
    }//GEN-LAST:event_player_playButtonMouseExited

    private void inputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFieldActionPerformed

    private void player_playButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_player_playButtonMouseClicked
       
    }//GEN-LAST:event_player_playButtonMouseClicked

    private void MinimizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonMouseClicked
           setState(JFrame.ICONIFIED);       // TODO add your handling code here:
    }//GEN-LAST:event_MinimizeButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainFrame().setVisible(true);
                } catch (MalformedURLException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AutomationHomePanel;
    private javax.swing.JLabel BedRoomNightLightBtn;
    private javax.swing.JLabel ExitButton;
    private javax.swing.JLabel MinimizeButton;
    private javax.swing.JPanel VideoPlayerPanel;
    private javax.swing.JLabel background;
    private javax.swing.JLabel bedRoom;
    private javax.swing.JLabel bedRoomACBtn;
    private javax.swing.JLabel bedRoomFanBtn;
    private javax.swing.JLabel bedRoomLightBtn;
    private javax.swing.JPanel bedRoomPanel;
    private javax.swing.JLabel bedRoomPanelBorder;
    private javax.swing.JLabel bedRoomTVBtn;
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel dailyNewsReader;
    private javax.swing.JLabel dailyNewsReaderBtn;
    private javax.swing.JLabel homeAuto;
    private javax.swing.JLabel homeAutoBtn;
    private javax.swing.JPanel homeAutomationParent;
    private javax.swing.JPanel homePanel;
    private javax.swing.JPanel infoExtractPanel;
    private javax.swing.JLabel infoExtractor;
    private javax.swing.JLabel infoExtractorBtn;
    private javax.swing.JTextField inputField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel kitchen;
    private javax.swing.JLabel livingRoom;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel mp3Player;
    private javax.swing.JLabel mp3PlayerBtn;
    private javax.swing.JLabel panelBtn1;
    private javax.swing.JLabel panelBtn2;
    private javax.swing.JLabel panelBtn3;
    private javax.swing.JLabel panelBtn4;
    private javax.swing.JLabel panelBtn5;
    private javax.swing.JLabel panelBtn6;
    private javax.swing.JLabel panelOpenClose;
    private javax.swing.JLabel personalRoom;
    private javax.swing.JLabel playerBorder;
    private javax.swing.JLabel player_inputField;
    private javax.swing.JLabel player_playButton;
    private javax.swing.JLabel sidePanel;
    private javax.swing.JLabel storeRoom;
    private javax.swing.JLabel videoPlayer;
    private javax.swing.JLabel videoPlayerBtn;
    private javax.swing.JLabel voiceBrowser;
    private javax.swing.JLabel voiceBrowserBtn;
    // End of variables declaration//GEN-END:variables
}
